load_module /usr/lib/nginx/modules/ngx_http_geoip2_module.so;

worker_processes auto;

events {
    worker_connections 1024;
}

http {

    include /etc/nginx/mime.types;

    default_type application/octet-stream;

    geoip2 /etc/nginx/geoip/GeoLite2-Country.mmdb {

        auto_reload 5m;

        $geoip2_data_country_code
        default=ZZ
        source=$remote_addr
        country iso_code;
    }

    server {

        listen 80;

        server_name venugeoloc.com;

        location / {

            if ($geoip2_data_country_code = IN) {
                return 302 http://venugeoloc-ind.com;
            }

            if ($geoip2_data_country_code = US) {
                return 302 http://venugeoloc-us.com;
            }

            proxy_pass http://global;
        }
    }

    server {

        listen 80;

        server_name venugeoloc-ind.com;

        location / {
            proxy_pass http://india;
        }
    }

    server {

        listen 80;

        server_name venugeoloc-us.com;

        location / {
            proxy_pass http://usa;
        }
    }
}